### ISSUE TITLE
question about FactorizedReduce

### ISSUE THREAD

**Issue by samuelstanton** [liamcli/darts#2]
Hi,
I'm attempting to reimplement some parts of DARTS and I had a couple questions about the FactorizedReduce operator

1) is this line correct? Won't the slicing of `x` cause a shape mismatch in the concatentation?
https://github.com/liamcli/darts/blob/master/cnn/operations.py#L102

2) Can you give some intuition for what this operator is supposed to do? In particular, why is it sometimes used as the `skip_connect` operator, instead of the `Identity` op?

**Comment by liamcli** [comment]
hi samuel, please note this is a fork of the original repository at https://github.com/quark0/darts.
